name: Update Linux Kernel

on:
  push:
    branches:
      - main

jobs:
  update-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Update Kernel
        id: update-kernel
        run: |
          latest_tag=$(curl -sS https://www.kernel.org/releases.json | jq -r '.latest_stable.version')
          echo "Latest Linux Kernel version: $latest_tag"
          echo "KERNEL_VERSION=$latest_tag" >> $GITHUB_ENV  # 将版本号写入环境文件

      - name: Write Version to Repository
        id: write-version
        if: steps.update-kernel.outcome == 'success'
        run: |
          version=${{ env.KERNEL_VERSION }}
          if [ -f kernel_version.txt ]; then
            echo >> kernel_version.txt  # 在文件的末尾插入一个空行
            echo "$version" >> kernel_version.txt  # 将新的版本号追加到文件的下一行
          else
            echo "$version" > kernel_version.txt  # 如果文件不存在，则创建新文件并写入版本号
          fi

      - name: Write Error Version to Repository
        id: write-error-version
        if: steps.update-kernel.outcome == 'failure'
        run: |
          version="000"
          if [ -f kernel_version.txt ]; then
            echo >> kernel_version.txt  # 在文件的末尾插入一个空行
            echo "$version" >> kernel_version.txt  # 将错误版本号追加到文件的下一行
          else
            echo "$version" > kernel_version.txt  # 如果文件不存在，则创建新文件并写入错误版本号
          fi
